### ISSUE TITLE
Password is passed unsanitized?

### ISSUE THREAD

**Issue by zhaw-munt** [fiware-academy/builder#1]
https://github.com/fiware-academy/builder/blob/master/config/memberDB.php#L28
which reads

``` php
$qry = "Select * from users where username='$username' and password='$password'";
```

embeds strings raw into a query. This means the caller has to do the proper sanitation which is bad practice because you'd need to do that at every call site and better hope you don't forget it anywhere.

One such call site seems to be
https://github.com/fiware-academy/builder/blob/master/config/memberABSTRACT.php#L51
which reads

``` php
if(!$this->Authentication($this->SanitizeForSQL($username),$password))return false;
```

which looks like the password is not sanitized. Also:

``` php
$username = trim($_POST['username']);
$password = trim($_POST['password']);
```

Why do you trim passwords?

**Comment by lecchereng** [comment]
Thank you for the analisys and the suggestions. We accepted your help for improving the tool.

**Comment by lecchereng** [comment]
Thank you for the analisys and the suggestions. We accepted your help for improving the tool.
