### ISSUE TITLE
Password replacement & arbitrary password change

### ISSUE THREAD

**Issue by zhaw-munt** [fiware-academy/builder#2]
https://github.com/fiware-academy/builder/blob/c569aceeed4c8d51f4438701e4fdbe6e4cd2c050/config/functions.php#L5
which reads

``` php
function prepareForSQL($str){
global $mysql;
$str = str_replace('"',"&quot;", $str);
$str = $mysql->real_escape_string($str);
return $str;
} 
```

This replaces `"` with the corresponding HTML-entities. This function is used for example at
https://github.com/fiware-academy/builder/blob/master/change_pwd.php#L28 which reads

``` php
$password = prepareForSQL($_POST['password']);
```

so basically if the user's password has a `"` in it the user's password will be mangled and now contains a `&qout;` and since it looks like that the Authentication-Methods use a different (and much better) SQL-Sanitation Method it would appear that a user can't login with his password because you're not storing the password the user actually entered. Additionally in the same file on line 34 there's a

``` php```
$sql = $sql . " WHERE id_user = $idn" ;
```

which is also a possible injection since `$idn` looks unsanitized. Also by reading the code `$idn = $_POST['id'];` and the later usage of `$idn` it seems that `$idn` is the user id but it doesn't appear to be checked whether this is the user id of the user who is actually logged in so you can basically provide the id of any user you want?

**Comment by lecchereng** [comment]
Thank you for the analisys and the suggestions. We accepted your help for improving the tool.
